<p><span style="font-weight: 400;">On April 6, 2024, 16-year-old Harper Tillman borrowed his friend’s e-scooter to take a quick trip down the street. Tillman was forced to ride on the street due to foot traffic on the sidewalk. The teenager ran a stop sign and was struck by a car. Soon after his body hit the pavement, he began to see flashing lights. He was paralyzed by confusion and pain. The crash left him with a concussion and a fractured spine, which forced him into a neck brace for months. His story is one of many cautionary tales about the safety issues presented by electric scooters, also known as e-scooters.</span></p>
<p> </p>
<p><span style="font-weight: 400;">E-scooters are intended to be a sustainable form of transportation that is quick and easy to use, but they are also unpredictable. Riders tend to avoid using protective gear, such as helmets and body pads. Minimal policies are put into place to protect riders and pedestrians on the streets. A 2023 study published by the National Highway Traffic Safety Administration (NHTSA) found that over 70% of riders who faced injuries were not wearing helmets at the time of their crash, increasing the severity of head injuries and fractures. E-scooter riders are twice as likely to suffer from head injuries than bicyclists due to lower rates of wearing helmets, which only 15% of e-scooter riders do.</span></p>
<p> </p>
<p><img class="post__image" src="file:///Users/nicoleclement/Documents/Publii/sites/smpa-3230/input/media/posts/6/Bike-vs-EScooter-Injuries.png" alt="An outline of the human body shows that bike riders have worse injuries in the torso, lower limbs, and road rash/abrasions. Internal injuries, upper limb fractures, and the head are more common in e-scooter riders." width="656" height="874"></p>
<div> </div>
<p><span style="font-weight: 400;">In the District, hospital admissions for e-scooter injuries increased by 18% in 2024, according to the District Department of Transportation (DDOT). Tillman was lucky to have faced injuries that healed in just months.</span></p>
<p><span style="font-weight: 400;">In Washington, DC, 52 people died in 2024 from e-scooter accidents, which is the same amount of e-scooter deaths in 2023. Between 2022-24, 433 severe injuries and over 3,600 minor injuries affected pedestrians, bicyclists, and e-scooter users due to the unsafe conditions for e-scooter riders. Most of the 68 fatal accidents occurred when motor vehicle drivers hit a person riding a bicycle or e-scooter, according to DDOT.</span><noscript><img src="https://datawrapper.dwcdn.net/b5Bxp/full.png" alt="" /></noscript></p>
<p><span style="font-weight: 400;">E-scooter collisions among other riders and bicyclists are rare. In three years, DDOT recorded seven crashes between riders colliding with each other. In other situations, riders tend to lose control of their e-scooters, causing a lot of pedestrian collisions on the sidewalks. Three of five e-scooter injuries occurred on sidewalks, while one in five happened in bike lanes or trails, according to a study conducted by The George Washington University Hospital. For the study over 100 e-scooter riders who ended up in their emergency room were interviewed between March and November 2019. E-scooter riders are far more likely to be injured or killed by cars than by each other. One of the key solutions to facilitating e-scooter safety is the availability of protected bike lanes.</span></p>
<p> </p>
<p><iframe style="width: 100%; height: 600px;" src="https://flo.uri.sh/visualisation/22943693/embed" title="Interactive or visual content" class="flourish-embed-iframe" frameborder="0" scrolling="no" sandbox="allow-same-origin allow-forms allow-scripts allow-downloads allow-popups allow-popups-to-escape-sandbox allow-top-navigation-by-user-activation"></iframe></p>
<div class="flourish-embed flourish-pictogram" data-src="visualisation/22943693">
<script src="https://public.flourish.studio/resources/embed.js"></script>
<noscript><img src="https://public.flourish.studio/visualisation/22943693/thumbnail" width="100%" alt="pictogram visualization showing what e-scooter riders are most likely to crash into. From least to greatest, the collisions occur with parked vehicles, another cyclist/scooter, pedestrians, moving vehicles, infrastructure (e.g. poles, curbs, fences), surface features (e.g. potholes, uneven pavement), and other." /></noscript></div>
<p><span style="font-weight: 400;">E-scooter riders often navigate a gray area as they are sometimes forced onto sidewalks, where collisions with pedestrians occur. Other times, they share the road with cars, where they face a much greater risk. The lack of designated space increases their vulnerability, making infrastructure improvements a vital solution. Cities with extensive bike lane networks have seen up to 40% fewer e-scooter crashes compared to cities that lack bike lanes, according to the National Association of City Transportation Officials. Washington Area Bicyclist Association (WABA) believes a bike lane network can reduce e-scooter crashes by up to 35%. The need for protected bike lanes is especially urgent in areas with high e-scooter and bicycle ridership. Cities that invest in designated paths for micro mobility users have reported lower accident rates and improved the flow of traffic, according to the League of American Bicyclists. Bike lane networks that are well-integrated reduce confusion and provide a clear space for e-scooter users to ride freely, without the traffic of vehicles or pedestrians. </span></p>
<p><span style="font-weight: 400;">A report from the DC Policy Center found that 62% of e-scooter riders feel unsafe due to poor infrastructure, including potholes and narrow streets. Many riders report avoiding certain routes altogether due to the high risk of collision. </span></p>
<p><span style="font-weight: 400;">"Protected bike lanes correlate with lower injury rates among all micro mobility users. The safer the infrastructure, the fewer collisions," said Seth Grimes, the DC organizer WABA.</span></p>
<p> </p>
<p><span style="font-weight: 400;">Lime Micromobility, the largest electric vehicle company in the world, released a report last fall showing a decrease in scooter crashes directly corresponding with an increase in bike lane mileage and usage. The data shows that as cities expand infrastructure for micro mobility users, fewer e-scooter riders are injured in traffic accidents.</span></p>
<p> </p>
<p><span style="font-weight: 400;">"If DC wants to truly commit to being a greener city, it should make e-scooters more accessible by improving infrastructure rather than restricting their use. Instead of policies that make it harder for residents to rely on scooters for short trips, the city should focus on expanding bike lanes and safer riding spaces to encourage sustainable transportation," said David Strickland, a former administrator of NHTSA.</span></p>
<p> </p>
<p><span style="font-weight: 400;">Despite the push for improved infrastructure, progress has been slow. City officials put focus on other transportation priorities. Micro mobility advocates argue that local politicians underestimate the urgency of bike lane expansion as e-scooters are still seen as a novelty, instead of a legitimate mode of transportation.</span></p>
<p> </p>
<div id="datawrapper-vis-ueZ3G" style="min-height: 346px;">
<script type="text/javascript" defer="defer" src="https://datawrapper.dwcdn.net/ueZ3G/embed.js" charset="utf-8" data-target="#datawrapper-vis-ueZ3G"><br></script>
</div>
<div> </div>
<div><span style="font-weight: 400;">The Vice President for Research at the Insurance Institute for Highway Safety,  Jessica Cicchino, studied e-scooter crashes extensively, focusing on how they happen and how riders get injured. Her findings reveal that more e-scooter injuries occur on sidewalks than streets. Riders often flock to the sidewalk to avoid riding in unfazed traffic, mixed with motor vehicles. Ironically, riding on the sidewalk leads to unintended risks such as uneven pavement, pedestrians stepping into riders’ paths, and abrupt stops that force riders to swerve or fall. Cicchino explains that e-scooter riders are not choosing sidewalks because they want to, but because they feel they have to. Without protected bike lanes, riders are forced into dangerous situations, as they dodge pedestrians and uneven sidewalks.</span></div>
<div> </div>
<div style="min-height: 346px;"><span style="font-weight: 400;">Beyond individual crashes, cities with strong bike lane networks consistently report lower injury rates for e-scooter users, proving that infrastructure plays a significant role in accident prevention. A report from the DC Policy Center found that 62% of e-scooter riders feel unsafe due to poor infrastructure, particularly the potholes and narrow streets.</span>
<div> </div>
<div><span style="font-weight: 400;">The District Department of Transportation's Micromobility Dashboard tracks patterns in e-scooter usage, pointing to key locations where riders struggle to find safe passage. Areas lacking bike lanes tend to see higher reports of collisions or swerve to avoid crashing.</span></div>
<div> </div>
<div id="datawrapper-vis-b5Bxp" style="min-height: 789px;">
<script type="text/javascript" defer="defer" src="https://datawrapper.dwcdn.net/b5Bxp/embed.js" charset="utf-8" data-target="#datawrapper-vis-b5Bxp"></script>
<noscript><img src="https://datawrapper.dwcdn.net/b5Bxp/full.png" alt="A chloropleth shows which wards have had the most crashes. The dek says 'Wards 5 and 8 have the most e-scooter crashes, which are labelled with having a high severity. Their bike lane presence is limited.'" /></noscript></div>
<div><span style="font-weight: 400;">Businesses that rely on e-scooter services have also voiced frustration over the lack of infrastructure. Delivery couriers using e-scooters have reported challenges navigating streets safely, often forced to take detours or risk dangerous interactions with cars. They are expected to deliver items quickly, but they struggle to do so safely. </span></div>
<div><span style="font-weight: 400;">“Navigating DC’s streets on an e-scooter for deliveries is unpredictable and often unsafe. I’m constantly forced to weave between traffic,” said Alex Ramirez, a delivery courier who relied on e-scooters for the past two years.</span></div>
<div> </div>
<div><span style="font-weight: 400;">Despite their risks, e-scooters have some safety advantages built into them. DC’s shared-mobility scooters are limited to speeds of 10 MPH, causing for less of an impact in case of a crash. Compared to cars or motorcycles, e-scooters also have less mass and momentum, making them less capable of causing severe damage in a crash. </span></div>
<div> </div>
<div><span style="font-weight: 400;">Still, the overwhelming carnage caused by motor vehicles have made e-scooters a dangerous form of transportation. While e-scooters are often considered the sole problem for safety concerns, the data shows that drivers are overwhelmingly responsible for micro mobility deaths. The solution is not to restrict scooters, rather improving streets to make them safer for all forms of transportation.</span></div>
<div> </div>
<div><span style="font-weight: 400;">City officials have implemented some regulations to address micro mobility concerns, such as designated parking areas and speed restrictions. These measures still do not tackle the root issue, which is the need for more protected bike lanes and more policy to ensure the safety of riders.</span></div>
<div> </div>
<div> </div>
<div><img class="post__image" src="file:///Users/nicoleclement/Documents/Publii/sites/smpa-3230/input/media/posts/6/bigger-e-scooter-timeline.png" alt="Timeline of e-scooter policies from when they popularized in DC to now." width="1798" height="1312"></div>
<p> </p>
<div> </div>
<div class="align-center"><span style="font-weight: 400;">Without substantial infrastructure improvements, riders will continue to face unnecessary risks. As scooter usage increases, DC has an opportunity to rethink urban mobility so teenagers like Tillman can safely ride e-scooters.</span></div>
<div> </div>
<div><span style="font-weight: 400;">E-scooters are just the beginning of a broader conversation about urban mobility and infrastructure, serving as a test for how cities are able to adapt to emerging transportation needs. While their convenience and accessibility make them a valuable tool for short trips, the lack of dedicated infrastructure forces riders into unsafe conditions. Without designated lanes, e-scooter users must constantly navigate a balancing act between crowded sidewalks and dangerous roads.</span></div>
<div> </div>
<div><span style="font-weight: 400;">More bike lanes would not only protect e-scooter users but also benefit bicyclists, pedestrians, and even drivers by reducing unpredictable distractions. As micro mobility continues to grow, the demand for better infrastructure will only intensify. Cities that prioritize safe travel spaces will see fewer crashes, along with minimal collisions between different transportation modes. With the right investments, urban areas can shift toward sustainable mobility that protects all road users.</span></div>
<p> </p>
</div>
